import json
from pathlib import Path
import tomllib

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_JSON_PATH = ROOT / "resources/gen/manifest.json"
MANIFEST_MODULE_PATH = ROOT / "src/dlii_labeler/gen/manifest.py"

with (ROOT / "pyproject.toml").open("rb") as pyproject:
	toml = tomllib.load(pyproject)

# Build the app manifest. Keep it as a Python module so packaging does not
# require a platform-specific Qt resource compiler executable.
manifest = {
        "name": toml["project"]["name"],
        "display_name": toml["manifest"]["display-name"],
        "version": toml["project"]["version"],
        "organization": toml["manifest"]["organization"],
        "organization_domain": toml["manifest"]["organization-domain"]
}

MANIFEST_JSON_PATH.parent.mkdir(exist_ok=True, parents=True)
MANIFEST_JSON_PATH.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")

MANIFEST_MODULE_PATH.parent.mkdir(exist_ok=True, parents=True)
MANIFEST_MODULE_PATH.write_text(
    "# Generated by scripts/build_resources.py; do not edit manually.\n"
    f"MANIFEST = {manifest!r}\n",
    encoding="utf-8",
)
